### ISSUE TITLE
Build issues: Can you provide the versions of JDK and Ghidra

### ISSUE THREAD

**Issue by li-xin-yi** [OSUSecLab/FirmXRay#1]
I followed the instructions in `README.md` to build FirmXRay. I copied `ghidra.jar` built from v9.0.1 or v10.0.3, either failed to create a `FirmXRay.md`, it only resulted in a warning message:

```
$make
javac -cp "lib/*" -d out @target.txt
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

So when I tried to run the test example:

```
$make run PATH=examples/Nordic/example_nordic.bin MCU=Nordic
java -cp out:lib/ghidra.jar:lib/json.jar main.Main examples/Nordic/example_nordic.bin Nordic
make: execvp: java: Not a directory
make: *** [Makefile:32: run] Error 127
```

I have

```
$java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

I'm not sure where I configured improperly. Can you help me with the environment issue?

Thank you very much.

**Comment by onehouwong** [comment]
Hello, the Ghidra version tested was v9.0.4, but I guess the issue comes from Java. Can you specify the full path of your java executable at [line5](https://github.com/OSUSecLab/FirmXRay/blob/master/Makefile#L5) of the Makefile?

FYI, I can execute with the following Java version.
```
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

Please feel free to reach out if you have other questions!

**Comment by li-xin-yi** [comment]
Thanks for your help. I figured out that it has nothing to do with version issues. After specifying the full path of java executable installed by open-JDK, it runs properly (except that it requires a root privilege to create `/usr/local/FirmXRay`).

Anyway, thank you very much.
