### ISSUE TITLE
Base address detection max bound too low for some firmware images

### ISSUE THREAD

**Issue by stokworks** [OSUSecLab/FirmXRay#2]
I've been using the base address detection component of FirmXRay in some of my own research, and have been applying it to the Cortex-M images in https://github.com/ucsb-seclab/monolithic-firmware-collection. After some debugging I have noticed that for images with base addresses above `0x80000`, the detection code seems to return addresses that do not make sense. A base address of `0x08000000` seems to be quite common in firmware images I have encountered.

`Constant.MAX_BASE`  is defined in https://github.com/OSUSecLab/FirmXRay/blob/master/src/main/Constant.java#L16. Increasing this value solves the problem. `MAX_BASE` is used to limit where functions and strings may exist in a firmware image. As such, `MAX_BASE` should be increased to a higher value than `0x08000000` to produce correct results for such images.

`Constant.MAX_BASE = 0x08000000 + program size` seems like a sensible value, but `Integer.MAX_VALUE` produces correct results for me as well.

**Comment by onehouwong** [comment]
Hi, Thanks a lot for the useful comment. I will update the code for a higher base address upper limit so that it works for other firmware images as well!
