### ISSUE TITLE
Extend to other Vendors 

### ISSUE THREAD

**Issue by MrMatch246** [OSUSecLab/FirmXRay#3]
Hey I'd like to use FirmXRay for Cypress devices or other Vendors.
What would i have to do to make that work ? is there any docu on extending that i didnt find?

**Comment by onehouwong** [comment]
Hi, you probably need to refer to the Cypress's (or other vendor's) SDK documentation for developing those devices. This one might be of interest: https://infineon.github.io/bless/ble_api_reference_manual/html/index.html. 

What you need to do is to identify the corresponding BLE related API functions (as in [here](https://github.com/OSUSecLab/FirmXRay/blob/master/src/main/Constant.java#L22)). You also need to figure out how these functions are called (e.g., whether they are directly called or are triggered with svc interrupts) in the device firmware code. Note that FirmXRay supports ARM Cortex-M architecture.
